[Icon Theme]
Name=Spider-Man-Red
Comment=Spider-Man red folders for Omarchy
Inherits=Yaru-dark
Example=folder
Directories=16x16/places,24x24/places,32x32/places,48x48/places,256x256/places

[16x16/places]
Context=Places
Size=16
Type=Fixed

[24x24/places]
Context=Places
Size=24
Type=Fixed

[32x32/places]
Context=Places
Size=32
Type=Fixed

[48x48/places]
Context=Places
Size=48
Type=Fixed

[256x256/places]
Context=Places
Size=256
MinSize=64
MaxSize=256
Type=Scalable
