[menu]
background                = "#12131C"
background-alpha          = 1.0
text                      = "#6272A4"
border                    = "#E62429"
border-alpha              = 1.0
scrim                     = "#12131C"
scrim-alpha               = 0.5
selected-background       = "#E1E1E6"
selected-background-alpha = 0.08
selected-text             = "#E62429"
selected-border           = "#E62429"
selected-border-alpha     = 0.25