[menu]
background                = "#0B1120"
background-alpha          = 1.0
text                      = "#4b6cc4"
border                    = "#E50914"
border-alpha              = 1.0
scrim                     = "#0B1120"
scrim-alpha               = 0.5
selected-background       = "#F5F7FF"
selected-background-alpha = 0.08
selected-text             = "#E50914"
selected-border           = "#E50914"
selected-border-alpha     = 0.25
